package com.jatinvashisht.cleannotes.features.featureNote.data.local.database

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Data class to represent NoteEntity.
 *
 * Also act as table for the database.
 *
 * @param [primaryKey] Primary Key of the database, auto generated by room database.
 * @param [title] Title of the note.
 * @param [body] Body of the note.
 * @param [categories] List of categories that current note falls in.
 * @param [tags] List of tags applied to current note to get identified easily in future.
 *
 * @author Jatin Vashisht (https://www.github.com/jatinvashisht1)
 * */
@Entity("notetable")
data class NoteEntity(
    @PrimaryKey(autoGenerate = true)
    val primaryKey: Long? = null,
    val title: String = "",
    val body: String = "",
    val categories: List<String> = listOf(),
    val tags: List<String> = listOf(),
)
